// <auto-generated />
using System;
using ActorMovieApplication.DAO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ActorMovieApplication.Migrations
{
    [DbContext(typeof(ActorDbContext))]
    partial class ActorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("ActorMovieApplication.Models.ActorModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("actorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("actors");
                });

            modelBuilder.Entity("ActorMovieApplication.Models.MovieModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActorModelid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("desc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(1000);

                    b.Property<int>("rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("ActorModelid");

                    b.ToTable("movies");
                });

            modelBuilder.Entity("ActorMovieApplication.Models.MovieModel", b =>
                {
                    b.HasOne("ActorMovieApplication.Models.ActorModel", null)
                        .WithMany("movies")
                        .HasForeignKey("ActorModelid");
                });
#pragma warning restore 612, 618
        }
    }
}
