// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mvcwebapplication.Dao;

namespace mvcwebapplication.Migrations
{
    [DbContext(typeof(MvcWebApplicationDbContext))]
    partial class MvcWebApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");
#pragma warning restore 612, 618
        }
    }
}
